#!/bin/bash

set -xe

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <OS_TYPE> <OS_VERSION>"
    exit 1
fi

os_type="$1"
os_version="$2"

docker_args="-e OS_TYPE=$os_type -e OS_VERSION=$os_version -v $(pwd):/build:rw --rm=true"

case $os_type in
    centos|fedora)
        # check for correct package manager
        if [[ $os_type == "fedora" ]]; then
            YUM=dnf
        else
            YUM=yum
        fi

        # set up the docker image with a baseline
        cat >Dockerfile <<EOF
FROM $os_type:$os_version
RUN mkdir /build
VOLUME /build
RUN $YUM -y install rpm-build gcc git make readline-devel ncurses-devel
EOF
        sudo docker build -t nnn .

        # do the build
        sudo docker run $docker_args nnn /bin/bash -c "cd /build && ./redhat/build-rpm"
        ;;
    *)
        echo "$OS_TYPE $OS_VERSION not supported!"
        exit 1
        ;;
esac

# vim: et:ai:ts=4:sw=4
