.Dd May 12, 2017
.Dt NNN 1
.Os
.Sh NAME
.Nm nnn
.Nd the missing terminal file browser for X
.Sh SYNOPSIS
.Nm
.Op Ar -d
.Op Ar -i
.Op Ar -p custom_nlay
.Op Ar -S
.Op Ar -v
.Op Ar -h
.Op Ar PATH
.Sh DESCRIPTION
.Nm
(Noice is Not Noice) is a performance-optimized fork of the noice terminal file browser with extensive desktop integration, simplified navigation, \fInavigate-as-you-type\fR mode, disk usage analyzer mode, comprehensive file details and much more. It remains a simple and efficient file browser that stays out of your way.
.Pp
.Nm
defaults to the current directory if
.Ar PATH
is not specified.
.Pp
.Nm
supports both vi-like and emacs-like key bindings in the default
configuration. The default key bindings are listed below.
.Pp
.Bl -tag -width "l, [Right], [Return] or C-mXXXX" -offset indent -compact
.It Ic [Up], k, ^P
Move to previous entry
.It Ic [Down], j, ^N
Move to next entry
.It Ic [PgUp], ^U
Scroll up half a page
.It Ic [PgDn], ^D
Scroll down half a page
.It Ic [Home], g, ^, ^A
Move to the first entry
.It Ic [End], G, $, ^E
Move to the last entry
.It Ic [Right], [Enter], l, ^M
Open file or enter directory
.It Ic [Left], [Backspace], h, ^H
Back up one directory level
.It Ic [Insert]
Toggle navigate-as-you-type mode
.It Ic ~
Change to the HOME directory
.It Ic &
Change to initial directory
.It Ic -
Change to the last visited directory
.It Ic /
Change filter (more information below)
.It Ic ^/
Search directory in desktop search tool
.It Ic \&.
Toggle hide .dot files
.It Ic c
Change into the given directory
.It Ic d
Toggle detail view
.It Ic D
Toggle current file details screen
.It Ic m
Show concise mediainfo
.It Ic M
Show full mediainfo
.It Ic s
Toggle sort by file size
.It Ic S
Toggle disk usage analyzer mode
.It Ic t
Toggle sort by time modified
.It Ic \&!
Spawn SHELL in PWD (fallback sh)
.It Ic e
Open current entry in EDITOR (fallback vi)
.It Ic o
Open directory in NNN_DE_FILE_MANAGER
.It Ic p
Open current entry in PAGER (fallback less)
.It Ic ^K
Invoke file name copier
.It Ic ^L
Force a redraw
.It Ic \&?
Toggle help screen
.It Ic Q
Quit and change directory
.It Ic q, ^Q
Quit
.El
.Pp
Backing up one directory level will set the cursor position at the
directory you came out of.
.Pp
.Nm
supports the following options:
.Pp
.Fl d
        start in detail view mode
.Pp
.Fl i
        start in navigate-as-you-type mode
.Pp
.Fl "p custom_nlay"
        path to custom nlay
.Pp
.Fl S
        start in disk usage analyzer mode
.Pp
.Fl v
        show version and exit
.Pp
.Fl h
        show program help and exit
.Sh CONFIGURATION
.Nm
uses \fIxdg-open\fR (on Linux) and \fIopen(1)\fR (on OS X) as the desktop
opener. It invokes
.Pa nlay
to run desktop search utility or screensaver. Read more on
.Pa nlay
at:
.br
.Em https://github.com/jarun/nnn/wiki/all-about-nlay
.Pp
Configuring
.Nm
to change to the last visited directory on quit requires shell integration in a
few easy steps. Please visit the project page (linked below) for the
instructions.
.Sh FILTERS
Filters support regexes to display only the matched
entries in the current directory view. This effectively allows
searching through the directory tree for a particular entry. Matching entries
are shown instantly (search-as-you-type).
.Pp
Filters do not stack on top of each other. They are applied anew
every time. There are 4 ways to reset a filter: \fI^L\fR, an empty filter
expression, a search with no results or an extra backspace at the filter prompt
(like vi).
.Pp
If you want to list all matches starting with the filter expression (a common
use case), start the expression with a
.Pa ^
(caret) symbol.
.Pp
If
.Nm
is invoked as root the default filter will also match hidden files.
.Pp
In the \fInavigate-as-you-type mode\fR directories are opened in filter mode,
allowing continuous navigation. Works best with the \fBarrow keys\fR.
.Sh ENVIRONMENT
The SHELL, EDITOR and PAGER environment variables take precedence
when dealing with the !, e and p commands respectively.
.Pp
\fBNNN_USE_EDITOR:\fR use EDITOR (preferably CLI, fallback vi) to handle text
files.
.Bd -literal
        export NNN_USE_EDITOR=1
.Ed
.Pp
\fBNNN_DE_FILE_MANAGER:\fR set to a desktop file manager to open the current
directory with. E.g.:
.Bd -literal
        export NNN_DE_FILE_MANAGER=thunar
.Ed
.Pp
\fBNNN_IDLE_TIMEOUT:\fR set idle timeout (in seconds) to invoke terminal
screensaver.
.Pp
\fBNNN_COPIER:\fR set to a clipboard copier script. For example, on Linux:
.Bd -literal
        -------------------------------------
        #!/bin/sh

        echo -n $1 | xsel --clipboard --input
        -------------------------------------
.Ed
.Sh KNOWN ISSUES
If you are using urxvt you might have to set backspacekey to DEC.
.Sh AUTHORS
.An Lazaros Koromilas Aq Mt lostd@2f30.org ,
.An Dimitris Papastamos Aq Mt sin@2f30.org ,
.An Arun Prakash Jana Aq Mt engineerarun@gmail.com .
.Sh HOME
.Em https://github.com/jarun/nnn
