.Dd Oct 22, 2014
.Dt NOICE 1
.Os
.Sh NAME
.Nm noice
.Nd small file browser
.Sh SYNOPSIS
.Nm noice
.Op Ar dir
.Sh DESCRIPTION
.Nm
is a simple and efficient file browser that gets out of your way
as much as possible.  It was initially implemented to be controlled
with a TV remote control.
.Pp
.Nm
defaults to the current directory if
.Ar dir
is not specified.
.Pp
.Nm
supports both vi-like and emacs-like key bindings in the default
configuration.  The default key bindings are described below;
their functionality is described in more detail later.
.Pp
.Bl -tag -width "l | Right | Return | C-mXXXX" -offset indent -compact
.It Ic k | Up | C-p
Move to previous entry.
.It Ic j | Down | C-n
Move to next entry.
.It Ic Pgup | C-u
Scroll backwards one page.
.It Ic Pgdown | C-d
Scroll forwards one page.
.It Ic l | Right | Return | C-m
Open file or enter directory.
.It Ic h | Left | Backspace
Back up one directory level.
.It Ic / | &
Filter view (see below for more information).
.It Ic !
Spawn shell in current directory.
.It Ic c
Change into the given directory.
.It Ic q
Quit
.Nm .
.El
.Sh CONFIGURATION
.Nm
is configured by modifying
.Pa config.h
and recompiling the code.
.Pp
The file associations are specified by regexes
matching on the currently selected filename.  If a match is found the associated
program is executed with the filename passed in as the argument.  If no match
is found the program less(1) is invoked.  This is useful for editing text files
as one can use the 'v' command in less(1) to edit the file in $EDITOR.
.Pp
See the examples section below for more information.
.Sh FILTERS
Filters allow you to use regexes to display only the matched
entries in the current directory view.  This effectively allows
searching through the directory tree for a particular entry.
.Pp
Filters do not stack on top of each other.  They are applied anew
every time.
.Pp
To reset the filter you can use the match-any regex (i.e. '.').
.Pp
If
.Nm
is invoked as root the default filter will also match hidden
files.
.Sh HISTORY
.Nm
keeps track of the current cursor position per directory
level.  Backing up one directory level will restore the
cursor position at that level.
.Pp
History is discarded for the backed out directory.  In other
words, history is recorded only when entering directories.
.Sh EXAMPLES
The following example shows one possible configuration for
file associations.  This is the default configuration for
.Nm .
.Bd -literal
struct assoc assocs[] = {
        { "\\.(avi|mp4|mkv|mp3|ogg|flac)$", "mplayer" },
        { "\\.(png|jpg|gif)$", "feh" },
        { "\\.(html|svg)$", "firefox" },
        { "\\.pdf$", "mupdf" },
        { "\\.sh$", "sh" },
        { ".*", "less" },
};
.Ed
.Sh KNOWN ISSUES
In urxvt you might have to start your terminal with
backspacekey set to DEC.
.Pp
.Sh AUTHORS
.Nm
was developed by Lazaros Koromilas <lostd@2f30.org> with
contributions by sin <sin@2f30.org>.
