#!/usr/bin/env sh

# Description: Fuzzy find a file in directory subtree with fzy and open using xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

xdg-open `find -type f | fzy` >/dev/null 2>&1
