#!/usr/bin/env bash

# Description: Send the selected files to your Android device using kdeconnect-cli. You must have installed and configured kdeconnect both on the Android device and on the PC.
#
# Shell: Bash
# Author: juacq97

id=$(kdeconnect-cli -a --id-only | awk '{print $1}')
if [ $(find ~/.nnncp) ]
then
    kdeconnect-cli -d $id --share $(cat ~/.nnncp)
# If you want a system notification, uncomment the next 3 lines.
#    notify-send -a "Kdeconnect" "Sending $(cat ~/.nnncp)"
#else
#    notify-send -a "Kdeconnect" "No file selected"
fi
