#!/usr/bin/env sh

# Description: Copy selection to clipboard
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

SELECTION=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection

# Linux
cat "$SELECTION" | xargs -0 | xsel -bi

# macOS
# cat "$SELECTION" | xargs -0 | pbcopy

# Termux
# cat "$SELECTION" | xargs -0 | termux-clipboard-set

# Cygwin
# cat "$SELECTION" | xargs -0 | clip

# Wayland
# cat "$SELECTION" | xargs -0 | wl-copy
