#!/usr/bin/env sh

# Description: Navigate to directory using autojump
#
# Dependencies: autojump - https://github.com/wting/autojump
#
# Note: autojump STORES NAVIGATION PATTERNS
#
# Shell: POSIX compliant
# Author: Marty Buchaus

if [ -z "$NNN_PIPE" ]; then
    echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
    exit 2
fi

if which autojump >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(autojump "$dir")"
    printf "%s" "0c$odir" > "$NNN_PIPE"
else
    printf "autojump missing"
    read -r _
fi
