#!/usr/bin/env sh

# Description: Navigate to directory using jump/autojump
#
# Dependencies: jump - https://github.com/gsamokovarov/jump
#               OR autojump - https://github.com/wting/autojump
#
# Note: jump/autojump STORES NAVIGATION PATTERNS
#
# Shell: POSIX compliant
# Authors: Marty Buchaus, Dave Snider

if [ -z "$NNN_PIPE" ]; then
    echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
    exit 2
fi

if which jump >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(jump cd "$dir")"
    printf "%s" "0c$odir" > "$NNN_PIPE"
elif which autojump >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(autojump "$dir")"
    printf "%s" "0c$odir" > "$NNN_PIPE"
else
    printf "jump/autojump missing"
    read -r _
fi
