#!/usr/bin/env sh

# Description: Navigate to directory using autojump
#
# Requires: autojump - https://github.com/wting/autojump
#
# Note: autojump STORES NAVIGATION PATTERNS
#
# Shell: POSIX compliant
# Author: Marty Buchaus

if which autojump >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(autojump "$dir")"
    printf "%s" "0$odir" > "$NNN_PIPE"
else
    printf "autojump missing"
    read -r _
fi
