#!/usr/bin/env sh

# Description: Run fzf and go to the directory of the file selected
# Note: by adding an environment variable called FZF_DEFAULT_COMMAND
# it's possible to manipulate the default collection of items
# piped to fzf. For Example:
#   export FZF_DEFAULT_COMMAND="fd -H --type d . $HOME"
# Then all paths piped to fzf are absolute and therefore
# they need to be handled in such a way by this plugin.
#
# Shell: POSIX compliant
# Author: Anna Arad

. "$(dirname "$0")"/.nnn-plugin-helper

if [ "$(cmd_exists fzf)" -eq "0" ]; then
	sel=$(fzf)
else
	exit 1
fi

if [ -n "$sel" ]; then
	if ! [ -d "$sel" ]; then
		sel=$(dirname "$sel")
    elif [ "$sel" = "." ]; then
        exit 0
	fi

    # Check if selected path returned
    # by fzf command is absolute and
    # change directory then without
    # further manipulation
    case $sel in
    /*) nnn_cd "$sel" ;;
    *)  
        # Remove "./" prefix if it exists
        sel="${sel#./}"
        
        if [ "$PWD" = "/" ]; then
            nnn_cd "/$sel"
        else
            nnn_cd "$PWD/$sel"
        fi;;
    esac    
fi