#!/usr/bin/env sh

# Description: Fuzzy find a file in directory subtree with fzy
#              Opens in $VISUAL or $EDITOR if text
#              Opens other type of files with xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

entry="$(find -type f 2>/dev/null | fzy)"

case "$(file -biL "$entry")" in
    *text*)
        "${VISUAL:-$EDITOR}" "$entry" ;;
    *)
        xdg-open "$entry" >/dev/null 2>&1 ;;
esac
