#!/usr/bin/env sh

# Description: cd to the top level of the current git repository in the current context
# Dependencies: git
# Shell: sh
# Author: https://github.com/PatrickF1

if git rev-parse --git-dir > /dev/null 2>&1; then
    root="$(git rev-parse --show-toplevel)"
    printf "%s" "0c$root" > "$NNN_PIPE"
else
    printf "Not in a git repository"
    read -r _
    exit 1
fi
