#!/usr/bin/env bash

# Description: gpg encryption
#
# Note: symmetric encryption only works for a single file as per gpg limitations
#
# Shell: POSIX compliant
# Author: KlzXS

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

printf "(s)ymmetric, (a)symmetric? [default=a] "
read -r symmetry

files=$(tr '\0' '\n' < "$selection")
if [ "$symmetry" = "s" ]; then
	gpg --symmetric "$files"
else
	keyids=$(gpg --list-public-keys --with-colons | grep -E "pub:(.*:){10}.*[eE].*:" | awk -F ":" '{print $5}')

	#awk needs literal $10
	#shellcheck disable=SC2016
	keyuids=$(printf "%s" "$keyids" | xargs -n1 -I{} sh -c 'gpg --list-key --with-colons "{}" | grep "uid" | awk -F ":" '\''{printf "%s %s\n", "{}", $10}'\''')

	recipient=$(printf "%s" "$keyuids" | fzf | awk '{print $1}')

	printf "%s" "$files" | xargs -n1 gpg --encrypt --recipient "$recipient"
fi

