#!/usr/bin/env sh

#set -x
# Description: Send the selected files to your Android device using gsconnect daemon.js.
#              GSConnect must be configured on the Android device and the PC.
#
# Shell: POSIX compliant
# Author: Darukutsu 

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
gsconnect=$HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
id=$($gsconnect -l)

if [ -s "$selection" ]; then
    IFS=$'\n'
    for file in $(cat -t $selection | sed "s/\^\@/\n/g"); do
    	$gsconnect -d "$id" --share-file="$file"
    done 
else
    notify-send -a "GSConnect" "No files selected"
fi
    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
