#!/usr/bin/env sh

# Description: Resize images in a directory to screen resolution with imgp
# imgp homepage: https://github.com/jarun/imgp
#
# Notes:
# 1. Set res if you don't want to be prompted for desktop resolution every time
# 2. minsize is set to 1MB by default, adjust it if you want
# 3. imgp options used:
#       a - adaptive mode
#       c - convert PNG to JPG
#       k - skip images matching specified hres/vres
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

# set resolution (e.g. 1920x1080)
res=

# set minimum image size (in bytes) to resize (default: 1MB)
minsize=1048576

if [ -z "$res" ]; then
    echo -n "desktop resolution (hxv): "
    read res
fi

if ! [ -z "$res" ] && ! [ -z "$minsize" ]; then
    imgp -ackx "$res" -s "$minsize"
fi
