#!/usr/bin/env sh

# Description: View thumbnail of an image or a directory of images with lsix
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if ! [ -z "$1" ]; then
    if [ -d "$1" ]; then
        lsix "$1"/*
    else
        lsix "$1"
    fi

    printf "Press any key to exit..."
    read -r _
fi
