#!/usr/bin/env sh

# Description: Shows the external IP address and whois information. Useful over VPNs.
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

IP=$(curl -s ifconfig.me)

whois "$IP"
echo your external IP address is "$IP"

read -r _
