#!/usr/bin/env sh

# Description: Send the selected files to your Android device using kdeconnect-cli.
#              kdeconnect must be configured on the Android device and the PC.
#
# Shell: POSIX compliant
# Author: juacq97

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

id=$(kdeconnect-cli -a --id-only | awk '{print $1}')
if [ -s "$selection" ]; then
    kdeconnect-cli -d "$id" --share "$(cat "$selection")"

    # If you want a system notification, uncomment the next 3 lines.
    #notify-send -a "Kdeconnect" "Sending $(cat "$selection")"
#else
    #notify-send -a "Kdeconnect" "No file selected"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
fi
