#!/usr/bin/env sh

# Description: Send the selected files to your Android device using kdeconnect-cli. You must have installed and configured kdeconnect both on the Android device and on the PC.
#
# Shell: POSIX compliant
# Author: juacq97

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

id=$(kdeconnect-cli -a --id-only | awk '{print $1}')
if [ "$(find "$selection")" ]; then
    kdeconnect-cli -d "$id" --share "$(cat "$selection")"
# If you want a system notification, uncomment the next 3 lines.
#    notify-send -a "Kdeconnect" "Sending $(cat "$selection")"
#else
#    notify-send -a "Kdeconnect" "No file selected"
fi
