#!/usr/bin/env sh

# Description: Show media information of a file in pager
#
# Requires: mediainfo
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if ! [ -z "$1" ] && [ -f "$1" ]; then
    mediainfo "$1" | $PAGER
    # exiftool "$1" | $PAGER
fi
