#!/usr/bin/env sh

# Description: Backup of all nnn config
#
# Shell: POSIX compliant
# Author: Léo Villeveygoux

nnn_names="n nnn"

outfile="nnn-$(whoami)@$(hostname).tar.bz2"

shellname="$(basename "$SHELL")"

shellfile="config.$shellname"

configdir="${XDG_CONFIG_HOME:-$HOME/.config}/nnn"

workdir="$PWD"

tempdir="$(mktemp -d)"

if [ ! -d "$tempdir" ]; then
	echo "Can't create work directory." >&2
	exit 1
fi

cd "$tempdir" || exit 1

# Environment config
env | sed "s/'/'\\\\''/" |\
	awk '/^NNN_/{print "export '\''"$0"'\''"}' > "$shellfile"

# Shell functions/aliases
case "$shellname" in
	bash)
		for name in $nnn_names ; do
			if [ "$(type -t "$name")" = "function" ] ; then
				type "$name" | tail -n+2 >> "$shellfile"
			elif alias "$name" >/dev/null 2>&1 ; then
				alias "$name" >> "$shellfile"
			fi
		done
		;;
	zsh)
		for name in $nnn_names ; do
			if functions "$name" ; then
				functions "$name" >> "$shellfile"
			elif alias "$name" ; then
				echo alias "$(alias "$name")" >> "$shellfile"
			fi
		done
		;;

	*)
		echo "Unknown shell, skipping alias/function checking." >&2
		;;
esac

# Config dir backup
if [ -d "$configdir" ] ; then
	cp -r "$configdir" config.d
fi

printf "Saving as '%s' ... " "$workdir/$outfile"

tar caf "$workdir/$outfile" ./* && echo "Done" || echo "Failed"

cd "$workdir" && rm -rf "$tempdir"

