#!/usr/bin/env sh

# Description: Backup of all nnn config
#
# Shell: POSIX compliant
# Author: Léo Villeveygoux

nnn_aliases="n nnn"

outdir="nnn-$(whoami)@$(hostname)"

outfile="${outdir}.tar.bz2"

shellname="$(basename "$SHELL")"

conffile="config.txt"

configdir="${XDG_CONFIG_HOME:-$HOME/.config}/nnn"

workdir="$PWD"

bak() {
	if [ -e "$1.bak" ] ; then
		bak "$1.bak" || return 1
	fi
	mv "$1" "$1".bak || return 1
}

tempdir="$(mktemp -d)"

if [ ! -d "$tempdir" ]; then
	echo "Can't create work directory." >&2
	exit 1
fi

cd "$tempdir" || exit 1

# Backing up config dir content
cp -r "$configdir" "$outdir" || mkdir "$outdir" || exit 1

cd "$outdir" || exit 1

if [ -e "$conffile" ] ; then
	bak "$conffile"
fi

# Environment config
env | sed "s/'/'\\\\''/" |\
	awk '/^NNN_/{print "export '\''"$0"'\''"}' > "$conffile"

# Shell functions/aliases
case "$shellname" in
	bash)
		for name in $nnn_aliases ; do
			if [ "$(bash -c "type -t $name")" = "function" ] ; then
				bash -c "type $name" | tail -n+2 >> "$conffile"
			elif alias "$name" >/dev/null 2>&1 ; then
				alias "$name" >> "$conffile"
			fi
		done
		;;
	zsh)
		for name in $nnn_aliases ; do
			if functions "$name" ; then
				functions "$name" >> "$conffile"
			elif alias "$name" ; then
				echo alias "$(alias "$name")" >> "$conffile"
			fi
		done
		;;

	*)
		echo "Unknown shell, skipping alias/function checking." >&2
		;;
esac

cd .. || exit 1

printf "Saving as '%s' ... " "$workdir/$outfile"

tar caf "$workdir/$outfile" "$outdir" && echo "Done" || echo "Failed"

cd "$workdir" && rm -rf "$tempdir"

