#!/usr/bin/env sh

# Description: Open a quick notes file or directory in $EDITOR
#
# Details: Set the variable NOTE to the path to your quick notes file
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

NOTE=
# NOTE=~/Dropbox/Notes/synced_note

if [ ! -z "$NOTE" ]; then
   $EDITOR "$NOTE"
fi
