#!/usr/bin/env sh

# Description: List files bigger than input size by ascending access date.
#
# Requires: find sort
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

printf "Min file size (MB): "
read -r size

find . -size +"$size"M -type f -printf '%A+ %s %p\n' | sort

echo "Press any key to exit"
read -r _
