#!/usr/bin/env sh

# Description: Paste contents of a text a file http://ix.io
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if ! [ -z "$1" ]; then
    curl -F "f:1=@$1" ix.io
    read -r _
fi
