#!/usr/bin/env sh

# Description: Open images in hovered  directory and thumbnails
#              open hovered image in sxiv and browse other images in the directory
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if command -v sxiv >/dev/null 2>&1; then
    if ! [ -z "$1" ]; then
        if [ -f "$1" ]; then
            sxiv -q "$PWD"
        elif [ -d "$1" ] || [ -h "$1" ]; then
            sxiv -qt "$1"
        fi
    fi
else
    echo "sxiv missing"
    read dummy
fi
