#!/usr/bin/env sh

# Description: Simple script to give copy-paste a progress percentage
#              by utilizing rsync. This may be so simple,
#              but a little bit too complicated to implement as an alias
#              or command plugin inside nnn.
#
#              Recommended key bind: NNN_PLUG='p:verbosepaste;'
#              So you can paste marked selections by pressing `;p`.
#
#              LIMITATION: this won't work when pasting to MTP device.
#
# Dependencies: rsync
#
# Shell: POSIX compliant
# Author: Benawi Adha

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -f "$sel" ]; then

    # Choose one of these two schemes by commenting

    # more verbose
    xargs -0 -a "$sel" -I % rsync -ah --progress % "$PWD"

    # less verbose
    # xargs -0 -a "$sel" -I % rsync -ah --info=progress2 % "$PWD"

fi
