#!/usr/bin/env sh

# Description: Generate video thumbnails and view them
#
# Dependencies:
#    ffmpegthumbnailer: https://github.com/dirkvdb/ffmpegthumbnailer
#    lsix: https://github.com/hackerb9/lsix
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

mkdir .nthumbs > /dev/null 2>&1

for file in *; do
    if [ -f "$file" ]; then
        ffmpegthumbnailer -i "$file" -o .nthumbs/"${file%%.*}".jpg 2> /dev/null
    fi
done

# render thumbnails in lsix
lsix .nthumbs/*

# remove the thumbnails
rm -rf .nthumbs

printf "Press any key to exit..."
read -r _
