#!/usr/bin/env sh

# Description: View an image or images in a directory in pager
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

if ! [ -z "$1" ]; then
    if [ -d "$1" ]; then
        viu -n "$1"/* 2>/dev/null | less -R
    else
        viu -n "$1" | less -R
    fi
fi
