#!/usr/bin/env sh

# Description: Navigate to directory using zoxidep
#
# Dependencies: zoxide - https://github.com/ajeetdsouza/zoxide
#
# Shell: POSIX compliant
# Author: Tim Adler

if which zoxide >/dev/null 2>&1; then
    printf "jump to: "
    read -r dir
    odir="$(zoxide query -- "$dir")"
    printf "%s" "0c$odir" > "$NNN_PIPE"
else
    printf "zoxide missing"
    read -r _
fi
