.Dd Mar 14, 2018
.Dt NLAY 1
.Os
.Sh NAME
.Nm nlay
.Nd a bash script to play files in different apps by file type or run some actions.
.Sh SYNOPSIS
.Nm
file/path type/action
.Sh DESCRIPTION
.Nm
is shipped with \fInnn\fR to deliver a level of flexibility to users to choose their own apps when running some actions, run some commands or custom scripts. It has provisions to handle text files too. However, the capability is not used in the latest releases. Now
.Nm
is invoked to run a desktop search (\fIgnome-search-tool\fR or \fIcatfish\fR) or screen locker (\fIvlock\fR or \fIbashlock\fR or \fIlock\fR) utility. However,
.Nm
can run independently and can be highly customized for personal usage.
.Pp
.Nm
supports the following options:
.Pp
"file/path"
        The first argument can be the file or path to pass as an argument to the app. It can also be an empty string e.g., while locking the terminal.
.Pp
"type/action"
        This can be any of the strings \fItext\fR, \fIsearch\fR, \fIscript\fR or \fIlocker\fR.
.Sh USAGE
.Pp
.Bd -literal
$ nlay info.txt text
$ nlay . search
$ nlay ~/script.sh script
$ nlay "" locker
.Ed
.Sh AUTHOR
.An Arun Prakash Jana Aq Mt engineerarun@gmail.com .
.Sh HOME
.Em https://github.com/jarun/nnn
