#ifndef ICONS_EMOJI
#define ICONS_EMOJI

#define MD_ARROW_UPWARD    "⬆️"
#define MD_ARROW_FORWARD   "➡️"
#define MD_ARROW_DOWNWARD  "⬇️"

#define EMOJI_ARCHIVE "📦"
#define EMOJI_AUDIO "🎵"
#define EMOJI_BINARY "📓"
#define EMOJI_BOOKS "📚"
#define EMOJI_BRIEFCASE "💼"
#define EMOJI_C "📑"
#define EMOJI_CHANGELOG "🔖"
#define EMOJI_CLOUD "☁️ "
#define EMOJI_CODE "🧮"
#define EMOJI_CONF "🔧"
#define EMOJI_CPP EMOJI_C
#define EMOJI_DATABASE "🗃️ "
#define EMOJI_DESKTOP "🖥️ "
#define EMOJI_DIFF "📋"
#define EMOJI_DISK "💿"
#define EMOJI_DOWNLOAD "📥"
#define EMOJI_ENCRYPTED "🔒"
#define EMOJI_EXE "⚙️ "
#define EMOJI_FILE "📄"
#define EMOJI_FOLDER "📂"
#define EMOJI_GAME "🧩"
#define EMOJI_GIT "🌱"
#define EMOJI_IMAGE "🖼️ "
#define EMOJI_INFO "ℹ️ "
#define EMOJI_JAVA "☕"
#define EMOJI_JAVASCRIPT EMOJI_SCRIPT
#define EMOJI_LICENSE "⚖️ "
#define EMOJI_LINUX "🐧"
#define EMOJI_LUA "🌘"
#define EMOJI_MAKE "🚧"
#define EMOJI_MANUAL "📔"
#define EMOJI_MOVIE "🎬"
#define EMOJI_MUSIC EMOJI_AUDIO
#define EMOJI_NOTE "📝"
#define EMOJI_NOTES "📓"
#define EMOJI_PATCH "🩹"
#define EMOJI_PDF "📕"
#define EMOJI_PHOTO "📸"
#define EMOJI_PICTURE EMOJI_IMAGE
#define EMOJI_PRESENTATION "📊"
#define EMOJI_PUBLIC "👀"
#define EMOJI_PYTHON "🐍"
#define EMOJI_RSS "📡"
#define EMOJI_RUBY "💎"
#define EMOJI_SCRIPT "📜"
#define EMOJI_STATS "📊"
#define EMOJI_STYLESHEET "🎨"
#define EMOJI_SUBTITLES "💬"
#define EMOJI_TABLE "📗"
#define EMOJI_TEMPLATE "📎"
#define EMOJI_TEXT "🗒️ "
#define EMOJI_UNI "🏛️ "
#define EMOJI_VECTOR "🗺️ "
#define EMOJI_WEB "🌍"
#define EMOJI_WINDOWS "🪟"
#define EMOJI_WORD "📘"
#define EMOJI_WORK EMOJI_UNI

#endif // ICONS_EMOJI
